#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo
echo "Checking your typescript code..."
npx tsc --noEmit || (
    echo "There's syntax error in your code, please check again";
    echo
    false;
)
