name: Build executable and Deploy
on:
    push:
        branches:
            - main

jobs:
    build-exe:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: main
            - name: Install Dependencies
              run: |
                  npm install
            - name: Build executable
              run: |
                  npm run build
                  npm run build:exe
                  cp -r ./files ./executable
                  git add -f executable/*
            - name: Commit changes
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git commit -m "Update executable"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  branch: executable
